package VagrantfileLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class FileProvisioningDeclaration_BehaviorDescriptor extends AbstractProvisioningDeclaration_BehaviorDescriptor implements ProvisioningDeclaration_BehaviorDescriptor {
  public String virtual_getCodeName_6655287260023332180(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "VagrantfileLanguage.structure.FileProvisioningDeclaration";
  }

}
