package VagrantfileLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class MachineDeclaration_Behavior {
  public static void call_BO_up_1570195135974314154(SNode __thisNode__) {
    MachineDeclaration__BehaviorDescriptor.BO_up_id1nat2wFMT2E(__thisNode__);
  }
}
