package VagrantfileLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface ProvisioningDeclaration_BehaviorDescriptor {
  public String virtual_getCodeName_6655287260023332180(SNode thisNode);
}
