package VagrantfileLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Vagrantfile_Behavior {
  public static void call_BO_generate_1570195135974616995(SNode __thisNode__) {
    Vagrantfile__BehaviorDescriptor.BO_generate_id1nat2wFO2Yz(__thisNode__);
  }
  public static void call_BO_up_1570195135974727403(SNode __thisNode__) {
    Vagrantfile__BehaviorDescriptor.BO_up_id1nat2wFOtVF(__thisNode__);
  }
}
