package VagrantfileLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class VirtualBoxProviderDeclaration_BehaviorDescriptor extends AbstractProviderDeclaration_BehaviorDescriptor implements ProviderDeclaration_BehaviorDescriptor {
  public String virtual_getCodeName_6655287260023315561(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "VagrantfileLanguage.structure.VirtualBoxProviderDeclaration";
  }

}
