package VagrantfileLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum BOX_GUEST {
  LINUX("LINUX", "LINUX"),
  WINDOWS("WINDOWS", "WINDOWS"),
  MACOSX("MACOSX", "MACOSX");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private BOX_GUEST(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<BOX_GUEST> getConstants() {
    List<BOX_GUEST> list = ListSequence.fromList(new LinkedList<BOX_GUEST>());
    ListSequence.fromList(list).addElement(BOX_GUEST.LINUX);
    ListSequence.fromList(list).addElement(BOX_GUEST.WINDOWS);
    ListSequence.fromList(list).addElement(BOX_GUEST.MACOSX);
    return list;
  }
  public static BOX_GUEST getDefault() {
    return BOX_GUEST.LINUX;
  }
  public static BOX_GUEST parseValue(String value) {
    if (value == null) {
      return BOX_GUEST.getDefault();
    }
    if (value.equals(BOX_GUEST.LINUX.getValueAsString())) {
      return BOX_GUEST.LINUX;
    }
    if (value.equals(BOX_GUEST.WINDOWS.getValueAsString())) {
      return BOX_GUEST.WINDOWS;
    }
    if (value.equals(BOX_GUEST.MACOSX.getValueAsString())) {
      return BOX_GUEST.MACOSX;
    }
    return BOX_GUEST.getDefault();
  }
}
