package VagrantfileLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class BOX_GUEST_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<BOX_GUEST> constants = ListSequence.fromList(BOX_GUEST.getConstants()).iterator();
    while (constants.hasNext()) {
      BOX_GUEST constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<BOX_GUEST> constants = ListSequence.fromList(BOX_GUEST.getConstants()).iterator();
    while (constants.hasNext()) {
      BOX_GUEST constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    BOX_GUEST constant = BOX_GUEST.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }
}
