package VagrantfileLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum PROTOCOL {
  TCP("TCP", "TCP"),
  UDP("UDP", "UDP");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private PROTOCOL(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<PROTOCOL> getConstants() {
    List<PROTOCOL> list = ListSequence.fromList(new LinkedList<PROTOCOL>());
    ListSequence.fromList(list).addElement(PROTOCOL.TCP);
    ListSequence.fromList(list).addElement(PROTOCOL.UDP);
    return list;
  }
  public static PROTOCOL getDefault() {
    return PROTOCOL.TCP;
  }
  public static PROTOCOL parseValue(String value) {
    if (value == null) {
      return PROTOCOL.getDefault();
    }
    if (value.equals(PROTOCOL.TCP.getValueAsString())) {
      return PROTOCOL.TCP;
    }
    if (value.equals(PROTOCOL.UDP.getValueAsString())) {
      return PROTOCOL.UDP;
    }
    return PROTOCOL.getDefault();
  }
}
