package VagrantfileLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SPropertyId;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class BridgeDeclaration_Constraints extends BaseConstraintsDescriptor {
  public BridgeDeclaration_Constraints() {
    super(MetaIdFactory.conceptId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d951cdL));
  }
  @Override
  protected Map<SPropertyId, PropertyConstraintsDescriptor> getNotDefaultSProperties() {
    Map<SPropertyId, PropertyConstraintsDescriptor> properties = new HashMap<SPropertyId, PropertyConstraintsDescriptor>();
    properties.put(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d951cdL, 0x5c5c548073d951ceL), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d951cdL, 0x5c5c548073d951ceL), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "interface_name";
        return isNotEmptyString((SPropertyOperations.getString(propertyValue)));
      }
    });
    return properties;
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
