package VagrantfileLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SPropertyId;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class PortForwardingNetworkInterfaceDeclaration_Constraints extends BaseConstraintsDescriptor {
  public PortForwardingNetworkInterfaceDeclaration_Constraints() {
    super(MetaIdFactory.conceptId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bcL));
  }
  @Override
  protected Map<SPropertyId, PropertyConstraintsDescriptor> getNotDefaultSProperties() {
    Map<SPropertyId, PropertyConstraintsDescriptor> properties = new HashMap<SPropertyId, PropertyConstraintsDescriptor>();
    properties.put(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bcL, 0x5c5c548073d892bdL), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bcL, 0x5c5c548073d892bdL), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "guest";
        return isNotEmptyString((SPropertyOperations.getString(propertyValue)));
      }
    });
    properties.put(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bcL, 0x5c5c548073d892c0L), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bcL, 0x5c5c548073d892c0L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "host";
        return isNotEmptyString((SPropertyOperations.getString(propertyValue)));
      }
    });
    return properties;
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
