package VagrantfileLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class PrivateNetworkInterfaceDeclaration_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd19L, "use_dhcp")) == true || (SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd1bL, "Ip")) != null)) {
      tgs.append(",");
      tgs.newLine();
    }
    ctx.getBuffer().area().increaseIndent();
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd1dL, "auto_config")) == true) {
      tgs.indent();
      tgs.append("auto_config: true");
      tgs.newLine();
    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd19L, "use_dhcp"))) {
      tgs.indent();
      tgs.append("type: \"dhcp\"");
      tgs.newLine();
    }
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd1bL, "Ip")) != null)) {
      tgs.indent();
      tgs.append("ip: \"");
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892bbL, 0x5c5c548073d9fd1bL, "Ip")), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d951c2L, 0x5c5c548073d951c3L, "ip")));
      tgs.append("\"");
      tgs.newLine();
    }
    ctx.getBuffer().area().decreaseIndent();
  }
}
