package VagrantfileLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class SshDeclaration_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb23cL, "username")))) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getReferenceLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbc997L, "Machine")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(".ssh.username = \"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb23cL, "username")));
      tgs.append("\"");
      tgs.newLine();
    }

    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb23eL, "password")))) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getReferenceLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbc997L, "Machine")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(".ssh.password = \"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb23cL, "username")));
      tgs.append("\"");
      tgs.newLine();
    }

    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb25fL, "forward_agent"))) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getReferenceLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbc997L, "Machine")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(".ssh.forward_agent = ");
      tgs.append((SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb25fL, "forward_agent")) == true ? "true" : "false"));
      tgs.newLine();
    }

    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb27dL, "insert_key"))) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getReferenceLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbc997L, "Machine")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(".ssh.insert_key = ");
      tgs.append((SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb27dL, "insert_key")) == true ? "true" : "false"));
      tgs.newLine();
    }

    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb24aL, "private_key_path")))) {
      tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getReferenceLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbc997L, "Machine")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
      tgs.append(".ssh.private_key_path = \"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0xda82f5d88dbb231L, 0xda82f5d88dbb24aL, "private_key_path")));
      tgs.append("\"");
      tgs.newLine();
    }

  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
