package VagrantfileLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;

public class VirtualBoxProviderDeclaration_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    ctx.getBuffer().area().increaseIndent();
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec0L, "gui"))) {
      tgs.indent();
      tgs.append("virtualbox.gui = ");
      tgs.append((SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec0L, "gui")) == true ? "true" : "false"));
      tgs.newLine();
    }
    if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec5L, "linked_clone"))) {
      tgs.indent();
      tgs.append("virtualbox.linked_clone = ");
      tgs.append((SPropertyOperations.getBoolean(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec5L, "linked_clone")) == true ? "true" : "false"));
      tgs.newLine();
    }
    if (isNotEmptyString(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec2L, "name")))) {
      tgs.indent();
      tgs.append("virtualbox.name = \"");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073e6bec2L, "name")));
      tgs.append("\"");
      tgs.newLine();
    }

    if (SPropertyOperations.getInteger(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073ecf407L, "cpus")) > 0) {
      tgs.indent();
      tgs.append("virtualbox.cpus = ");
      tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073ecf407L, "cpus")) + "");
      tgs.newLine();
    }
    if (SPropertyOperations.getInteger(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073ecf40cL, "memory_mb")) > 0) {
      tgs.indent();
      tgs.append("virtualbox.memory = ");
      tgs.append(SPropertyOperations.getInteger(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073ecf40cL, "memory_mb")) + "");
      tgs.newLine();
    }

    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073d892a7L, "Customizations"))).count() > 0) {
      for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x324207e1b3174582L, 0x8d4e0163a5a3cf3eL, 0x5c5c548073d892a6L, 0x5c5c548073d892a7L, "Customizations"))) {
        tgs.appendNode(item);
      }
    }
    ctx.getBuffer().area().decreaseIndent();
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
